namespace MultiFunPlayer.Input;

public interface IInputGestureDescriptor;
internal interface ISimpleInputGestureDescriptor : IInputGestureDescriptor;
internal interface IAxisInputGestureDescriptor : IInputGestureDescriptor;